### ISSUE TITLE
AttributeError: 'module' object has no attribute 'argsort'

### ISSUE THREAD

**Issue by Dawson-huang** [soskek/captioning_chainer#1]
START training. # iter/epoch= 468
     total [#.................................................]  2.13%
this epoch [##########################################........] 85.33%
Traceback (most recent call last):
  File "train.py", line 161, in <module>
    main()
  File "train.py", line 157, in main
    trainer.run()
  File "/usr/local/lib/python2.7/dist-packages/chainer/training/trainer.py", line 299, in run
    entry.extension(self)
  File "/home/aaaa/tensorflow/image2text/captioning_chainer-master/utils.py", line 220, in __call__
    results = self.model.decode(vecs, k=self.k)
  File "/home/aaaa/tensorflow/image2text/captioning_chainer-master/nets.py", line 180, in decode
    F.log_softmax(concat_output).data, k=k)
  File "/home/aaaa/tensorflow/image2text/captioning_chainer-master/nets.py", line 44, in get_topk
    argsort = xp.argsort(output, axis=1)
AttributeError: 'module' object has no attribute 'argsort'

Is there a bug that lacks the development environment or the code?

**Comment by aonotas** [comment]
Hi @Dawson-huang 
Please tell me your `cupy` version.
```
>> import cupy
>> print(cupy.__version__)
```

I recommend you to upgrade cupy.
```
$ pip install --upgrade cupy
```
